name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        # Add any environment variables needed for build
        NODE_ENV: production
        
    - name: Copy 404.html for GitHub Pages SPA support
      run: |
        cp public/404.html dist/404.html
        echo "404.html copied to dist directory"
        
    - name: Verify build output
      run: |
        echo "Build directory contents:"
        ls -la dist/
        echo "Checking for required files:"
        test -f dist/index.html && echo "✓ index.html exists" || echo "✗ index.html missing"
        test -f dist/404.html && echo "✓ 404.html exists" || echo "✗ 404.html missing"
        test -f dist/_redirects && echo "✓ _redirects exists" || echo "✗ _redirects missing"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        # Ensure 404.html is included
        keep_files: false
        
    - name: Output deployment info
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "🚀 Deployment completed!"
        echo "Your site should be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
        echo "Note: It may take a few minutes for changes to be visible."
